# Generated by Django 5.2.5 on 2025-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('shoes', 'Sepatu'), ('clothing', 'Pakaian'), ('gear', 'Gear (Bola, Pelindung, Alat Latihan)'), ('accessories', 'Aksesoris'), ('lifestyle', 'Lifestyle / Merchandise')], default='update', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sizes', models.ManyToManyField(blank=True, to='main.size')),
            ],
        ),
    ]
