# Generated by Django 5.2.6 on 2025-09-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_sizes_delete_productsize_delete_size_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('shoes', 'Sepatu'), ('clothing', 'Pakaian'), ('gear', 'Gear (Bola, Pelindung, Alat Latihan)'), ('accessories', 'Aksesoris'), ('lifestyle', 'Lifestyle / Merchandise')], default='shoes', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Separate sizes with commas, e.g., 39,40,41 or S,M,L,XL', max_length=100),
        ),
    ]
